export PYTHONPATH=/Personal/fuxin/dfuxin/PROJECTS/Pacbio/cDNA_Cupcake/sequence/
minimap2 -t 30 -ax splice -uf --secondary=no -C5 /SGRNJ/Public/Database/genome/homo_sapiens/ensembl_92/Homo_sapiens.GRCh38.fa /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/06.dedup/dedup.fasta > /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.fasta.sam 2> /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.fasta.sam.log
sort -k 3,3 -k 4,4n /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.fasta.sam > /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.fasta.sorted.sam
collapse_isoforms_by_sam.py --input /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/06.dedup/dedup.fasta -s /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.fasta.sorted.sam -c 0.99 -i 0.95 --gen_mol_count -o /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge
python /Personal/fuxin/dfuxin/PROJECTS/Pacbio/9.Compare_Against_Annotation/SQANTI3-4.2/sqanti3_qc.py /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge.collapsed.gff /SGRNJ/Public/Database/genome/homo_sapiens/ensembl_92/Homo_sapiens.GRCh38.92.chr.gtf /SGRNJ/Public/Database/genome/homo_sapiens/ensembl_92/Homo_sapiens.GRCh38.fa --fl_count /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge.collapsed.abundance.txt -d /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform
python /Personal/fuxin/dfuxin/PROJECTS/Pacbio/9.Compare_Against_Annotation/SQANTI3-4.2/sqanti3_RulesFilter.py  /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge.collapsed_classification.txt /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge.collapsed_corrected.fasta /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge.collapsed.gff
gzip /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/06.dedup/dedup.info.csv
python /Personal/fuxin/dfuxin/PROJECTS/Pacbio/cDNA_Cupcake/singlecell/collate_FLNC_gene_info.py /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge.collapsed.group.txt /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/06.dedup/dedup.info.csv.gz /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge.collapsed_classification.filtered_lite_classification.txt /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/11.annotation/dedup.annotated.csv
python /Personal/fuxin/dfuxin/PROJECTS/Pacbio/cDNA_Cupcake/singlecell/make_seurat_input.py -i /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/11.annotation/dedup.annotated.csv -a /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/10.isoform/dedup.5merge.collapsed_classification.filtered_lite.gtf -o /SGRNJ03/randd/user/fuxin/Github_repo/Pacbio_Analysis/test/res/11.annotation
